package:
  name: flaapluc
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/jlenain/flaapluc.git
  # path: ..  # for preparation of releases only

requirements:
  build:
    - python 3.*
    - numpy 1.23.*
    - scipy 1.9.*
    - astropy 5.*
    - matplotlib 3.5.*
    - fermitools 2.*
    - ephem 4.*
    - urllib3 1.*
    - uncertainties 3.*
    # - git_url: https://github.com/gammapy/enrico.git  # enrico not installable via PIP: no setup.py

  run:
    - python 3.*
    - numpy 1.23.*
    - scipy 1.9.*
    - astropy 5.*
    - matplotlib 3.5.*
    - fermitools 2.*
    - ephem 4.*
    - urllib3 1.*
    - uncertainties 3.*

about:
  home: https://github.com/jlenain/flaapluc
  license: BSD
  license_file: LICENSE
  summary: Quick and dirty Fermi-LAT light curve analysis
  description: |
    Quickly generate Fermi-LAT light curves of your preferred sources, using the aperture photometry method. It basically assumes that the data set, within 1 degree around the source, is background-free. Thus, for publication purposes and to get final results, the likelihood approach is to be preferred.
  dev_url: https://github.com/jlenain/flaapluc

extra:
  build: |
    Build conda package with `conda build . -c fermi -c conda-forge`
