package:
  name: flaapluc
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/jlenain/flaapluc.git
  
requirements:
  build:
    - python 3.*
    - numpy
    - scipy
    - astropy
    - matplotlib
    - fermitools 2.*
    - ephem
    - pytz

  run:
    - python 3.*
    - numpy
    - scipy
    - astropy
    - matplotlib
    - fermitools 2.*
    - ephem

about:
  home: https://github.com/jlenain/flaapluc
  license: BSD
  license_file: LICENSE
